version: '3.4'

services:
  webdev.aspnetmvc:
    image: ${DOCKER_REGISTRY-}webdevaspnetmvc
    build:
      context: .\WebDev.AspNETMVC
      dockerfile: Dockerfile
    depends_on:
      - sql
  sql:
    image: microsoft/mssql-server-windows
    environment:
    - "ACCEPT_eula='Y'"
    - "sa_password=Microsoft#1234"