version: '3.4'

services:
  webdev.aspnetmvc:
    #Uncomment Line #6 to build image for 
    #image: webdevaspnetcore
    image: ${DOCKER_REGISTRY-}webdevaspnetmvc
    
    build:
      context: .\WebDev.AspNETMVC
      dockerfile: Dockerfile
    depends_on:
      - sql
  sql:
    image: microsoft/mssql-server-windows-developer
    environment:
    - "ACCEPT_EULA=Y"
    - "sa_password=Microsoft#1234"